FT: true
FeatureExtraction: VGG
PAD: true
Prediction: CTC
SequenceModeling: BiLSTM
Transformation: None
arch: VGG
batch_max_length: 2048
batch_ratio: '1'
batch_size: 64
beta1: 0.9
character_list: 0123456789!\#$%&'()*+,-./:;<=>?@[\]№_`{|}~ €₽ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдеёжзийклмнопрстуфхцчшщъыьэюяЂђЃѓЄєІіЇїЈјЉљЊњЋћЌќЎўЏџҐґҒғҚқҮүҲҳҶҷӀӏӢӣӨөӮӯ
contrast_adjust: 0.0
data_filtering_off: false
decode: greedy
eps: 1.0e-08
experiment_name: easyocr_finetuned
freeze_FeatureFxtraction: false
freeze_SequenceModeling: false
grad_clip: 5
hidden_size: 256
imgH: 500
imgW: 600
input_channel: 1
lang_char: ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдеёжзийклмнопрстуфхцчшщъыьэюяЂђЃѓЄєІіЇїЈјЉљЊњЋћЌќЎўЏџҐґҒғҚқҮүҲҳҶҷӀӏӢӣӨөӮӯ
lang_list:
- ru
- en
lr: 0.0005
network_params:
  hidden_size: 256
  input_channel: 1
  output_channel: 256
new_prediction: false
num_epoch: 5
num_fiducial: 20
num_iter: 5000
number: 0123456789
optim: false
output_channel: 256
rgb: false
rho: 0.95
saved_model: cyrillic_g2.pth
select_data: train
sensitive: true
symbol: '!"#$%&''()*+,-./:;<=>?@[\]№_`{|}~ €₽'
total_data_usage_ratio: 1.0
train_data: all_data
valInterval: 500
valid_data: all_data/en_val
workers: 6
